export const UPDATE_TICKET = 'UPDATE-TICKET'
export const COMMENT = 'COMMENT'
export const ADD_TAGS_TO_TICKET = 'ADD-TAGS-TO-TICKET'
export const ADD_FILES_TO_TICKET = 'ADD-FILES-TO-TICKET'
export const COMMENT_MENTION = 'COMMENT-MENTION'
export const ASSIGN_TICKET = 'ASSIGN-TICKET'
export const CREATE_TICKET = 'CREATE-TICKET'
export const PROJECT_CREATED = 'PROJECT_CREATED'
export const PROJECT_ASSIGNED = 'PROJECT_ASSIGNED'
export const PROJECT_UPDATED = 'PROJECT_UPDATED'
export const PROPOSAL_SENT = 'PROPOSAL_SENT'
export const PROPOSAL_RECEIVED = 'PROPOSAL_RECEIVED'
export const TASK_UPDATED = 'TASK_UPDATED'
export const TASK_CREATED = 'TASK_CREATED'
export const PROJECT_ARCHIVED = 'PROJECT_ARCHIVED'
export const MILESTONE_UPDATED = 'MILESTONE_UPDATED'


export const avatarType = [
    UPDATE_TICKET,
    COMMENT,
    COMMENT_MENTION,
    ASSIGN_TICKET,
    TASK_UPDATED,
    PROJECT_CREATED,
    PROJECT_ARCHIVED,
    MILESTONE_UPDATED
]
export const iconType = [ADD_TAGS_TO_TICKET, ADD_FILES_TO_TICKET, CREATE_TICKET, PROJECT_CREATED, PROJECT_ASSIGNED, PROPOSAL_SENT, PROPOSAL_RECEIVED, PROJECT_UPDATED, TASK_UPDATED, TASK_CREATED, PROJECT_ARCHIVED, MILESTONE_UPDATED]
