import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    // {
    //     key: 'app.sidebar.main',
    //     path: '',
    //     title: 'Main',
    //     translateKey: 'sidebar.main',
    //     icon: 'apps',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [ADMIN, USER],
    //     subMenu: [
    //         {
    //             key: 'app.dashboard',
    //             path: `${APP_PREFIX_PATH}/dashboard`,
    //             title: 'Dashboard',
    //             translateKey: 'app.sidebar.dashboard',
    //             icon: 'dashboard',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },

    //     ]
    // },

    /*{
         key: 'app.sidebar.settings',
         path: '',
         title: 'Account',
         translateKey: 'app.sidebar.settings',
         icon: 'account',
         type: NAV_ITEM_TYPE_COLLAPSE,
         authority: [ADMIN, USER],
         subMenu: [
             {
                 key: 'appsAccount.settings',
                 path: `${APP_PREFIX_PATH}/account/settings/profile`,
                 title: 'Settings',
                 translateKey: 'nav.appsAccount.settings',
                 icon: '',
                 type: NAV_ITEM_TYPE_ITEM,
                 authority: [ADMIN, USER],
                 subMenu: [],
             },
             {
                 key: 'appsAccount.invoice',
                 path: `${APP_PREFIX_PATH}/account/invoice/36223`,
                 title: 'Invoice',
                 translateKey: 'nav.appsAccount.invoice',
                 icon: '',
                 type: NAV_ITEM_TYPE_ITEM,
                 authority: [ADMIN, USER],
                 subMenu: [],
             },
             {
                 key: 'appsAccount.activityLog',
                 path: `${APP_PREFIX_PATH}/account/activity-log`,
                 title: 'Activity Log',
                 translateKey: 'nav.appsAccount.activityLog',
                 icon: '',
                 type: NAV_ITEM_TYPE_ITEM,
                 authority: [ADMIN, USER],
                 subMenu: [],
             },
             {
                 key: 'appsAccount.kycForm',
                 path: `${APP_PREFIX_PATH}/account/kyc-form`,
                 title: 'KYC Form',
                 translateKey: 'nav.appsAccount.kycForm',
                 icon: '',
                 type: NAV_ITEM_TYPE_ITEM,
                 authority: [ADMIN, USER],
                 subMenu: [],
             },
         ],
     },*/

    {
        key: 'apps.account',
        path: '',
        title: 'Account',
        translateKey: 'sidebar.account',
        icon: 'account',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'app.sidebar.profile',
                path: '',
                title: 'Profile',
                translateKey: 'app.sidebar.profile',
                icon: 'account',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAccount.settings',
                        path: `${APP_PREFIX_PATH}/account/settings/profile`,
                        title: 'Info',
                        translateKey: 'nav.appsAccount.settings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.kycForm',
                        path: `${APP_PREFIX_PATH}/account/kyc-form`,
                        title: 'KYC Form',
                        translateKey: 'nav.appsAccount.kycForm',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.activity',
                        path: `${APP_PREFIX_PATH}/account/activity`,
                        title: 'Activity',
                        translateKey: 'nav.appsAccount.activity',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ]
            }
            
        ]

    },

    {
        key: 'app.sidebar.workspace',
        path: '',   
        title: 'My Workspace',
        translateKey: 'sidebar.workspace',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'app.sidebar.projects',
                path: '',
                title: 'Projects',
                translateKey: 'app.sidebar.projects',
                icon: 'projects',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    // {
                    //     key: 'projects.ongoingprojects',
                    //     path: `${APP_PREFIX_PATH}/projects/ongoingprojects`,
                    //     title: 'Ongoing Projects',
                    //     translateKey: 'app.sidebar.projects.ongoingprojects',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'projects.createproject',
                    //     path: `${APP_PREFIX_PATH}/projects/createproject`,
                    //     title: 'Create Project',
                    //     translateKey: 'app.sidebar.projects.createproject',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'projects.draftprojects',
                    //     path: `${APP_PREFIX_PATH}/projects/draftprojects`,
                    //     title: 'Draft Projects',
                    //     translateKey: 'app.sidebar.projects.draftprojects',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'projects.publishedprojects',
                    //     path: `${APP_PREFIX_PATH}/projects/publishedprojects`,
                    //     title: 'Published Projects',
                    //     translateKey: 'app.sidebar.projects.publishedprojects',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'projects.completedprojects',
                    //     path: `${APP_PREFIX_PATH}/projects/completedprojects`,
                    //     title: 'Completed Projects',
                    //     translateKey: 'app.sidebar.projects.completedprojects',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'projects.projectdashboard',
                        path: `${APP_PREFIX_PATH}/projects/projectdashboard`,
                        title: 'Dashboard',
                        translateKey: 'app.sidebar.projects.projectdashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'projects.allprojects',
                        path: `${APP_PREFIX_PATH}/projects/allprojects`,
                        title: 'Project List',
                        translateKey: 'app.sidebar.projects.allprojects',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'projects.draftprojects',
                        path: `${APP_PREFIX_PATH}/projects/draftprojects`,
                        title: 'Draft Projects',
                        translateKey: 'app.sidebar.projects.draftprojects',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'projects.publishedprojects',
                    //     path: `${APP_PREFIX_PATH}/projects/publishedprojects`,
                    //     title: 'Published Projects',
                    //     translateKey: 'app.sidebar.projects.publishedprojects',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'projects.scrumboard',
                        path: `${APP_PREFIX_PATH}/projects/scrumboard`,
                        title: 'Scrum Board',
                        translateKey: 'app.sidebar.projects.scrumboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'projects.issue',
                    //     path: `${APP_PREFIX_PATH}/projects/issue`,
                    //     title: 'Issue',
                    //     translateKey: 'app.sidebar.projects.issue',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },
            {
                key: 'app.sidebar.podsandpodjinns',
                path: '',
                title: 'Pods & Podjinns',
                translateKey: 'app.sidebar.podsandpodjinns',
                icon: 'podsandpodjinn',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'app.sidebar.podsandpodjinns.podjinn',
                        path: `${APP_PREFIX_PATH}/podsandpodjinns/podjinn`,
                        title: 'Podjinn',
                        translateKey: 'app.sidebar.projects.ongoingprojects.dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'app.sidebar.podsandpodjinns.managepods',
                        path: ``,
                        title: 'Manage Pods',
                        translateKey: 'app.sidebar.projects.ongoingprojects.calendar',
                        icon: '',
                        type: NAV_ITEM_TYPE_COLLAPSE,
                        authority: [ADMIN, USER],
                        subMenu: [
                            {
                                key: 'app.sidebar.podsandpodjinns.managepods.pods',
                                path: `${APP_PREFIX_PATH}/podsandpodjinns/pods`,
                                title: 'Pods',
                                translateKey: 'app.sidebar.projects.ongoingprojects.dashboard',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN, USER],
                                subMenu: [],
                            },
                            {
                                key: 'app.sidebar.podsandpodjinns.managepods.publishedpods',
                                path: `${APP_PREFIX_PATH}/podsandpodjinns/publishedpods`,
                                title: 'Published Pods',
                                translateKey: 'app.sidebar.projects.ongoingprojects.dashboard',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN, USER],
                                subMenu: [],
                            },
                           
                            // {
                            //     key: 'app.sidebar.podsandpodjinns.managepods.proposedlists',
                            //     path: `${APP_PREFIX_PATH}/podsandpodjinns/proposedlists`,
                            //     title: 'Proposed List',
                            //     translateKey: 'app.sidebar.projects.ongoingprojects.dashboard',
                            //     icon: '',
                            //     type: NAV_ITEM_TYPE_ITEM,
                            //     authority: [ADMIN, USER],
                            //     subMenu: [],
                            // },
                            {
                                key: 'app.sidebar.podsandpodjinns.managepods.archivedlist',
                                path: `${APP_PREFIX_PATH}/podsandpodjinns/archivedlist`,
                                title: 'Archived List',
                                translateKey: 'app.sidebar.projects.ongoingprojects.dashboard',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN, USER],
                                subMenu: [],
                            },
                        ],
                    },
                ],
            },
        ]
    },

    {
        key: 'app.sidebar.commcenter',
        path: '',
        title: 'Communication',
        translateKey: 'sidebar.commcenter',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'app.sidebar.commcenter',
                path: '',
                title: 'Comm Center',
                translateKey: 'app.sidebar.commcenter',
                icon: 'commcenter',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'commcenter.chat',
                        path: `${APP_PREFIX_PATH}/commcenter/chat`,
                        title: 'Chat',
                        translateKey: 'app.sidebar.commcenter.chat',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'commcenter.meetings',
                        path: `${APP_PREFIX_PATH}/commcenter/meetings`,
                        title: 'Meetings',
                        translateKey: 'app.sidebar.commcenter.meetings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [
                            {
                                key: 'commcenter.meetings.googlemeet',
                                path: `${APP_PREFIX_PATH}/commcenter/meetings/googlemeet`,
                                title: 'Google Meet',
                                translateKey: 'app.sidebar.commcenter.googlemeet',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN, USER],
                                subMenu: [],
                            },
                            {
                                key: 'commcenter.meetings.zoom',
                                path: `${APP_PREFIX_PATH}/commcenter/meetings/zoom`,
                                title: 'Zoom',
                                translateKey: 'app.sidebar.commcenter.zoom',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN, USER],
                                subMenu: [],
                            },
                        ],
                    },
                ],
            },
        ]
    },

    {
        key: 'app.sidebar.leadacquisition',
        path: '',
        title: 'Lead Acquisition',
        translateKey: 'sidebar.leadacquisition',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'app.sidebar.pipelinemanagement',
                path: '',
                title: 'Pipeline Management',
                translateKey: 'app.sidebar.pipelinemanagement',
                icon: 'pipeline',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    

                    {
                        key: 'pipeline.dashboard',
                        path: `${APP_PREFIX_PATH}/pipeline/dashboard`,
                        title: 'Dashboard',
                        translateKey: 'app.sidebar.pipeline.dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'pipeline.leads',
                        path: `${APP_PREFIX_PATH}/pipeline/leads`,
                        title: 'Leads',
                        translateKey: 'app.sidebar.pipeline.leads',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'pipelinemanagement.deals',
                        path: `${APP_PREFIX_PATH}/pipelinemanagement/deals`,
                        title: 'Deals',
                        translateKey: 'app.sidebar.pipelinemanagement.deals',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    /*{
                        key: 'pipeline.calendar',
                        path: `${APP_PREFIX_PATH}/pipeline/calendar`,
                        title: 'Calendar',
                        translateKey: 'app.sidebar.pipeline.calendar',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },*/
                    
                    /*{
                        key: 'pipeline.customerDetail',
                        path: `${APP_PREFIX_PATH}/pipeline/customer-details?id=8`,


                        title: 'Customers Detail',
                        translateKey: 'app.sidebar.pipeline.customerDetail',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'pipeline.customers',
                        path: `${APP_PREFIX_PATH}/pipeline/customers`,
                        title: 'Customers',
                        translateKey: 'app.sidebar.pipeline.customers',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'pipeline.mail',
                        path: `${APP_PREFIX_PATH}/pipeline/mail`,
                        title: 'Mail',
                        translateKey: 'app.sidebar.pipeline.mail',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },*/

                ],


            },



            // {
            //     key: 'app.sidebar.bidmanagement',
            //     path: '',
            //     title: 'Bid Management',
            //     translateKey: 'app.sidebar.bidmanagement',
            //     icon: 'bidmanagement',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'bidmanagement.availablebids',
            //             path: `${APP_PREFIX_PATH}/bidmanagement/availablebids`,
            //             title: 'Available Bids',
            //             translateKey: 'app.sidebar.bidmanagement.availablebids',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'bidmanagement.submittedbids',
            //             path: `${APP_PREFIX_PATH}/bidmanagement/submittedbids`,
            //             title: 'Submitted Bids',
            //             translateKey: 'app.sidebar.bidmanagement.submittedbids',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'bidmanagement.wonbids',
            //             path: `${APP_PREFIX_PATH}/bidmanagement/wonbids`,
            //             title: 'Won Bids',
            //             translateKey: 'app.sidebar.bidmanagement.wonbids',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'bidmanagement.lostbids',
            //             path: `${APP_PREFIX_PATH}/bidmanagement/lostbids`,
            //             title: 'Lost Bids',
            //             translateKey: 'app.sidebar.bidmanagement.lostbids',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'bidmanagement.expiredbids',
            //             path: `${APP_PREFIX_PATH}/bidmanagement/expiredbids`,
            //             title: 'Expired Bids',
            //             translateKey: 'app.sidebar.bidmanagement.expiredbids',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
        ]
    },

    {
        key: 'app.sidebar.reports',
        path: '',
        title: 'Reports',
        translateKey: 'sidebar.reports',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'app.sidebar.anm',
                path: '',
                title: 'Audit & Performance',
                translateKey: 'app.sidebar.anm',
                icon: 'anm',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    // {
                    //     key: 'anm.maxxqa',
                    //     path: `${APP_PREFIX_PATH}/anm/maxxqa`,
                    //     title: `MaxxQA`,
                    //     translateKey: 'app.sidebar.anm.maxxqa',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'anm.SalesDashboard.dashboard',
                        path: `${APP_PREFIX_PATH}/anm/SalesDashboard/dashboard`,
                        title: 'Dashboard',
                        translateKey: 'app.sidebar.anm.SalesDashboard.dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'anm.maxxstations.activitylog',
                        path: `${APP_PREFIX_PATH}/anm/maxxstations/activitylog`,
                        title: 'Activity Log',
                        translateKey: 'app.sidebar.anm.maxxstations.activitylog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'anm.LogList',
                        path: `${APP_PREFIX_PATH}/anm/LogList`,
                        title: 'Log List',
                        translateKey: 'app.sidebar.anm.LogList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'anm.ScreenLog',
                        path: `${APP_PREFIX_PATH}/anm/ScreenLog`,
                        title: 'Screen Log',
                        translateKey: 'app.sidebar.anm.ScreenLog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    
                    // {
                    //     key: 'anm.maxxstations',
                    //     path: `${APP_PREFIX_PATH}/anm/maxxstations`,
                    //     title: 'MaxxStations',
                    //     translateKey: 'app.sidebar.anm.maxxstations',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_COLLAPSE,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [
                    //         // {
                    //         //     key: 'anm.maxxstations.maxxstations',
                    //         //     path: `${APP_PREFIX_PATH}/anm/maxxstations/maxxstations`,
                    //         //     title: 'MaxxStations',
                    //         //     translateKey: 'app.sidebar.anm.maxxstations.maxxstations',
                    //         //     icon: '',
                    //         //     type: NAV_ITEM_TYPE_ITEM,
                    //         //     authority: [ADMIN, USER],
                    //         //     subMenu: [],
                    //         // },
                           
                    //         // {
                    //         //     key: 'anm.maxxstations.quantifytask',
                    //         //     path: `${APP_PREFIX_PATH}/anm/maxxstations/quantifytask`,
                    //         //     title: 'Quantify Tasks',
                    //         //     translateKey: 'app.sidebar.anm.maxxstations.quantifytask',
                    //         //     icon: '',
                    //         //     type: NAV_ITEM_TYPE_ITEM,
                    //         //     authority: [ADMIN, USER],
                    //         //     subMenu: [],
                    //         // },
                    //         // {
                    //         //     key: 'anm.maxxstations.manuallog',
                    //         //     path: `${APP_PREFIX_PATH}/anm/maxxstations/manuallog`,
                    //         //     title: 'Manual Log',
                    //         //     translateKey: 'app.sidebar.anm.maxxstations.manuallog',
                    //         //     icon: '',
                    //         //     type: NAV_ITEM_TYPE_ITEM,
                    //         //     authority: [ADMIN, USER],
                    //         //     subMenu: [],
                    //         // },
                    //     ],
                    // },
                    // {
                    //     key: 'anm.djinnhub',
                    //     path: `${APP_PREFIX_PATH}/anm/djinnhub`,
                    //     title: 'DjinnHub',
                    //     translateKey: 'app.sidebar.anm.djinnhub',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'anm.disputesnflags',
                        path: `${APP_PREFIX_PATH}/anm/disputesnflags`,
                        title: 'Flags & Disputes',
                        translateKey: 'app.sidebar.anm.disputesnflags',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'app.sidebar.rna',
                path: '',
                title: 'Report & Analysis',
                translateKey: 'app.sidebar.rna',
                icon: 'rna',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'rna.rnadashboard',
                        path: `${APP_PREFIX_PATH}/rna/rnadashboard`,
                        title: 'Dashboard',
                        translateKey: 'app.sidebar.rna.rnadashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rna.projectreport',
                        path: `${APP_PREFIX_PATH}/rna/projectreport`,
                        title: 'Project Report',
                        translateKey: 'app.sidebar.rna.projectreport',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rna.wagesreport',
                        path: `${APP_PREFIX_PATH}/rna/wagesreport`,
                        title: 'Wages Report',
                        translateKey: 'app.sidebar.rna.wagesreport',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rna',
                        path: `${APP_PREFIX_PATH}/rna`,
                        title: 'Log Reports',
                        translateKey: 'app.sidebar.rna',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [
                            {
                                key: 'rna.manualreports',
                                path: `${APP_PREFIX_PATH}/rna/manualreports`,
                                title: 'Manual Log',
                                translateKey: 'app.sidebar.rna.manualreports',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN, USER],
                                subMenu: [],
                            },

                        ],
                    },
                    {
                        key: 'rna.taskreport',
                        path: `${APP_PREFIX_PATH}/rna/taskreport`,
                        title: 'Task Report',
                        translateKey: 'app.sidebar.rna.taskreport',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    /* {
                        key: 'rna.revenuereport',
                        path: `${APP_PREFIX_PATH}/rna/revenuereport`,
                        title: 'Revenue Report',
                        translateKey: 'app.sidebar.rna.revenuereport',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rna.customreport',
                        path: `${APP_PREFIX_PATH}/rna/customreport`,
                        title: 'Custom Report',
                        translateKey: 'app.sidebar.rna.customreport',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rna.closurereport',
                        path: `${APP_PREFIX_PATH}/rna/closurereport`,
                        title: 'Closure Report',
                        translateKey: 'app.sidebar.rna.closurereport',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    }, */
                ],
            },
        ]
    },

    {
        key: 'app.sidebar.payment',
        path: '',
        title: 'Payment',
        translateKey: 'sidebar.payment',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'app.sidebar.paymentin',
                path: '',
                title: 'Payment In',
                translateKey: 'app.sidebar.paymentin',
                icon: 'paymentin',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    /* {
                        key: 'pin.clientpayments',
                        path: `${APP_PREFIX_PATH}/pin/clientpayments`,
                        title: 'Client Payments',
                        translateKey: 'app.sidebar.pin.clientpayments',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [

                           
                            {
                                key: 'pin.recentpayment',
                                path: `${APP_PREFIX_PATH}/pin/recentpayment`,
                                title: 'Recent Payments',
                                translateKey: 'app.sidebar.pin.recentpayment',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN, USER],
                                subMenu: [],
                            },
                            {
                                key: 'pin.ongoingapprovals',
                                path: `${APP_PREFIX_PATH}/pin/ongoingapprovals`,
                                title: 'Ongoing Approvals',
                                translateKey: 'app.sidebar.pin.ongoingapprovals',
                                icon: '',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN, USER],
                                subMenu: [],
                            },
                        ],
                    },
                    {
                        key: 'pin.wagespayments',
                        path: `${APP_PREFIX_PATH}/pin/wagespayments`,
                        title: 'Wages Payments',
                        translateKey: 'app.sidebar.pin.wagespayments',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    }, */

                    {
                        key: 'pin.payments-in-dashboard',
                        path: `${APP_PREFIX_PATH}/pin/payments-in-dashboard`,
                        title: 'Dashboard',
                        translateKey: 'app.sidebar.pin.payments-in-dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'pin.payments-in-invoice',
                        path: `${APP_PREFIX_PATH}/pin/payments-in-invoice`,
                        title: 'Invoices',
                        translateKey: 'app.sidebar.pin.payments-in-invoice',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'app.sidebar.paymentout',
                path: '',
                title: 'Payment Out',
                translateKey: 'app.sidebar.paymentout',
                icon: 'paymentout',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    /* {
                        key: 'pout.payments',
                        path: `${APP_PREFIX_PATH}/pout/payments`,
                        title: 'Payments',
                        translateKey: 'app.sidebar.pout.payments',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'pout.escrowpayment',
                        path: `${APP_PREFIX_PATH}/pout/escrowpayment`,
                        title: 'Escrow Payments',
                        translateKey: 'app.sidebar.pout.escrowpayment',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'pout.invoicepayments',
                        path: `${APP_PREFIX_PATH}/pout/invoicepayments`,
                        title: 'Invoice Payments',
                        translateKey: 'app.sidebar.pout.invoicepayments',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    }, */
                    {
                        key: 'pout.payments-out-dashboard',
                        path: `${APP_PREFIX_PATH}/pout/payments-out-dashboard`,
                        title: 'Dashboard',
                        translateKey: 'app.sidebar.pout.payments-out-dashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'pout.payments-out-invoice',
                        path: `${APP_PREFIX_PATH}/pout/payments-out-invoice`,
                        title: 'Invoices',
                        translateKey: 'app.sidebar.pout.payments-out-invoice',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
        ]
    },

    {
        key: 'app.sidebar.additional',
        path: '',
        title: 'Additional',
        translateKey: 'sidebar.additional',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [

            // {
            //     key: 'app.sidebar.cc',
            //     path: '',
            //     title: 'Campaign Console',
            //     translateKey: 'app.sidebar.cc',
            //     icon: 'account',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'cc.maxxresponse',
            //             path: `${APP_PREFIX_PATH}/cc/maxxresponse`,
            //             title: 'Maxxresponse',
            //             translateKey: 'app.sidebar.cc.maxxresponse',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'cc.maxxscore',
            //             path: `${APP_PREFIX_PATH}/cc/maxxscore`,
            //             title: 'Maxxscore',
            //             translateKey: 'app.sidebar.cc.maxxscore',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'cc.maxxifi',
            //             path: `${APP_PREFIX_PATH}/cc/maxxifi`,
            //             title: 'Maxxifi',
            //             translateKey: 'app.sidebar.cc.maxxifi',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            {
                key: 'app.sidebar.rating',
                path: '',
                title: 'Rating',
                translateKey: 'app.sidebar.rating',
                icon: 'rating',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'rating.ratingdashboard',
                        path: `${APP_PREFIX_PATH}/rating/ratingdashboard`,
                        title: 'Dashboard',
                        translateKey: 'app.sidebar.rating.ratingdashboard',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rating.ratepods',
                        path: `${APP_PREFIX_PATH}/rating/ratepods`,
                        title: 'Rate Pods',
                        translateKey: 'app.sidebar.rating.ratepods',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rating.ratejinns',
                        path: `${APP_PREFIX_PATH}/rating/ratejinns`,
                        title: 'Rate Jinns',
                        translateKey: 'app.sidebar.rating.ratejinns',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rating.rateprojects',
                        path: `${APP_PREFIX_PATH}/rating/rateprojects`,
                        title: 'Rate Projects',
                        translateKey: 'app.sidebar.rating.rateprojects',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rating.rateclients',
                        path: `${APP_PREFIX_PATH}/rating/rateclients`,
                        title: 'Rate Clients',
                        translateKey: 'app.sidebar.rating.rateclients',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'rating.ratepodjinn',
                        path: `${APP_PREFIX_PATH}/rating/ratepodjinn`,
                        title: 'Rate Podjinn',
                        translateKey: 'app.sidebar.rating.ratepodjinn',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'rating.wof',
                        path: `${APP_PREFIX_PATH}/rating/wof`,
                        title: 'Wall Of Fame',
                        translateKey: 'app.sidebar.rating.wof',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            // {
            //     key: 'app.sidebar.resourcemgmt',
            //     path: '',
            //     title: 'Resource Management',
            //     translateKey: 'app.sidebar.resourcemgmt',
            //     icon: 'account',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'resourcemgmt.admins',
            //             path: `${APP_PREFIX_PATH}/resourcemgmt/admins`,
            //             title: 'Admins',
            //             translateKey: 'app.sidebar.resourcemgmt.admins',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'resourcemgmt.inr',
            //             path: `${APP_PREFIX_PATH}/resourcemgmt/inr`,
            //             title: 'Invites And Requests',
            //             translateKey: 'app.sidebar.resourcemgmt.inr',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'resourcemgmt.allresources',
            //             path: `${APP_PREFIX_PATH}/resourcemgmt/allresources`,
            //             title: 'All Resources',
            //             translateKey: 'app.sidebar.resourcemgmt.allresources',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'resourcemgmt.manageclients',
            //             path: `${APP_PREFIX_PATH}/resourcemgmt/manageclients`,
            //             title: 'Manage Clients',
            //             translateKey: 'app.sidebar.resourcemgmt.manageclients',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'resourcemgmt.manageagencies',
            //             path: `${APP_PREFIX_PATH}/resourcemgmt/manageagencies`,
            //             title: 'Manage Agencies',
            //             translateKey: 'app.sidebar.resourcemgmt.manageagencies',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },

            // {
            //     key: 'app.sidebar.settings',
            //     path: '',
            //     title: 'Settings',
            //     translateKey: 'app.sidebar.settings',
            //     icon: 'account',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsAccount.settings',
            //             path: `${APP_PREFIX_PATH}/account/settings/profile`,
            //             title: 'Settings',
            //             translateKey: 'nav.appsAccount.settings',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.invoice',
            //             path: `${APP_PREFIX_PATH}/account/invoice/36223`,
            //             title: 'Invoice',
            //             translateKey: 'nav.appsAccount.invoice',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.activityLog',
            //             path: `${APP_PREFIX_PATH}/account/activity-log`,
            //             title: 'Activity Log',
            //             translateKey: 'nav.appsAccount.activityLog',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsAccount.kycForm',
            //             path: `${APP_PREFIX_PATH}/account/kyc-form`,
            //             title: 'KYC Form',
            //             translateKey: 'nav.appsAccount.kycForm',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
        ]
    },


]

export default appsNavigationConfig
